apiVersion: v1
kind: ConfigMap
metadata:
  name: ollama-backend-config
  namespace: ollama-agent
data:
  PORT: "5005"
  NODE_ENV: "production"
  OLLAMA_API: "http://ollama-service:11434/api"
  OLLAMA_MODEL: "tinyllama"
  # ✅ Browser origin = where the frontend is served from (nginx on port 3000)
  CORS_ORIGINS: "http://54.173.206.159:3000,http://localhost:3000,http://127.0.0.1:3000"

# kubectl patch configmap ollama-backend-config -n ollama-agent \
  # --type merge \
  # -p '{"data":{"CORS_ORIGINS":"http://18.209.95.132:3000,http://localhost:3000,http://127.0.0.1:3000"}}'

  
# apiVersion: v1 its old code 
# kind: ConfigMap
# metadata:
#   name: ollama-backend-config
#   namespace: ollama-agent
# data:
#   PORT: "5005"
#   NODE_ENV: "production"
#   OLLAMA_API: "http://ollama-service:11434/api"
#   OLLAMA_MODEL: "tinyllama"
#   CORS_ORIGIN: "http://ollama-frontend-service:80"
