apiVersion: v1
kind: ConfigMap
metadata:
  name: ollama-backend-config
  namespace: ollama-agent
data:
  PORT: "5005"
  NODE_ENV: "production"
  OLLAMA_API: "http://ollama-service:11434/api"
  OLLAMA_MODEL: "tinyllama"
  CORS_ORIGIN: "http://ollama-frontend-service:80"
