apiVersion: v1
kind: Service
metadata:
  name: ollama-backend-service
  namespace: ollama-agent
  labels:
    app: ollama-backend
spec:
  type: ClusterIP
  selector:
    app: ollama-backend
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
  ports:
    - name: http
      protocol: TCP
      port: 5005
      targetPort: 5005
