# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: backend-config
#   namespace: ollama-agent
# data:
#   PORT: "3000"
#   OLLAMA_URL: "http://ollama-service:11434"
#   OLLAMA_MODEL: "tinyllama"
#   NODE_ENV: "production"


apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: ollama-agent

data:
  PORT: "5005"
  NODE_ENV: "production"

  OLLAMA_API: "http://ollama-service:11434/api"   # ✅ FIXED

  OLLAMA_MODEL: "tinyllama"

  CORS_ORIGIN: "*"
  MAX_BODY_SIZE: "50mb"
  REQUEST_TIMEOUT: "120000"