apiVersion: v1
kind: Service
metadata:
  name: ollama-backend
  namespace: ollama-agent
spec:
  type: ClusterIP
  selector:
    app: ollama-backend
  ports:
    - name: http
      port: 5005
      targetPort: 5005