apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: mongodb-pvc
  namespace: ollama-agent

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: standard   # 👈 local cluster default

  resources:
    requests:
      storage: 10Gi
