apiVersion: v1
kind: Service
metadata:
  name: ollama-service
  namespace: ollama-agent
spec:
  type: ClusterIP
  selector:
    app: ollama
  ports:
    - name: ollama
      port: 11434
      targetPort: 11434
