apiVersion: v1
kind: Service
metadata:
  name: ollama-service
  namespace: ollama-agent
  labels:
    app: ollama
spec:
  type: ClusterIP
  selector:
    app: ollama
  ports:
    - name: ollama-api
      port: 11434
      targetPort: 11434
      protocol: TCP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
